spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://34.64.203.187:3306/db_dev?serverTimezone=Asia/Seoul&autoReconnect=true&useSSL=false
    username: db_dev_admin
    password: 1234
  rabbitmq:
    host: 34.64.89.15
    port: 5672
    username: guest
    password: guest
  cache:
    ehcache:
      config: classpath:ehcache.xml
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      open-in-view: false
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: info
  config: classpath:logback-${spring.profiles.active}.xml



